// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: admin_airline.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FlightTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tyupe string `protobuf:"bytes,2,opt,name=tyupe,proto3" json:"tyupe,omitempty"`
}

func (x *FlightTypeRequest) Reset() {
	*x = FlightTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightTypeRequest) ProtoMessage() {}

func (x *FlightTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightTypeRequest.ProtoReflect.Descriptor instead.
func (*FlightTypeRequest) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{1}
}

func (x *FlightTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlightTypeRequest) GetTyupe() string {
	if x != nil {
		return x.Tyupe
	}
	return ""
}

type FlightType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ManufacturerName    string `protobuf:"bytes,2,opt,name=manufacturer_name,json=manufacturerName,proto3" json:"manufacturer_name,omitempty"`
	ManufacturerCountry string `protobuf:"bytes,3,opt,name=manufacturer_country,json=manufacturerCountry,proto3" json:"manufacturer_country,omitempty"`
	FlightNumber        string `protobuf:"bytes,4,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	FlightType          string `protobuf:"bytes,5,opt,name=flight_type,json=flightType,proto3" json:"flight_type,omitempty"`
	Description         string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	MaxDistance         int32  `protobuf:"varint,7,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	MaxCruiseSpeed      int32  `protobuf:"varint,8,opt,name=max_cruise_speed,json=maxCruiseSpeed,proto3" json:"max_cruise_speed,omitempty"`
}

func (x *FlightType) Reset() {
	*x = FlightType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightType) ProtoMessage() {}

func (x *FlightType) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightType.ProtoReflect.Descriptor instead.
func (*FlightType) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{2}
}

func (x *FlightType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlightType) GetManufacturerName() string {
	if x != nil {
		return x.ManufacturerName
	}
	return ""
}

func (x *FlightType) GetManufacturerCountry() string {
	if x != nil {
		return x.ManufacturerCountry
	}
	return ""
}

func (x *FlightType) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *FlightType) GetFlightType() string {
	if x != nil {
		return x.FlightType
	}
	return ""
}

func (x *FlightType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlightType) GetMaxDistance() int32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

func (x *FlightType) GetMaxCruiseSpeed() int32 {
	if x != nil {
		return x.MaxCruiseSpeed
	}
	return 0
}

type FlightTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightType *FlightType `protobuf:"bytes,1,opt,name=flight_type,json=flightType,proto3" json:"flight_type,omitempty"`
	Code       int32       `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message    string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error      *Error      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FlightTypeResponse) Reset() {
	*x = FlightTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightTypeResponse) ProtoMessage() {}

func (x *FlightTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightTypeResponse.ProtoReflect.Descriptor instead.
func (*FlightTypeResponse) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{3}
}

func (x *FlightTypeResponse) GetFlightType() *FlightType {
	if x != nil {
		return x.FlightType
	}
	return nil
}

func (x *FlightTypeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FlightTypeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FlightTypeResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FlightTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlighTypes []*FlightType `protobuf:"bytes,1,rep,name=fligh_types,json=flighTypes,proto3" json:"fligh_types,omitempty"`
	Code       int32         `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message    string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error      *Error        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FlightTypesResponse) Reset() {
	*x = FlightTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightTypesResponse) ProtoMessage() {}

func (x *FlightTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightTypesResponse.ProtoReflect.Descriptor instead.
func (*FlightTypesResponse) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{4}
}

func (x *FlightTypesResponse) GetFlighTypes() []*FlightType {
	if x != nil {
		return x.FlighTypes
	}
	return nil
}

func (x *FlightTypesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FlightTypesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FlightTypesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AirlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AirlineRequest) Reset() {
	*x = AirlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirlineRequest) ProtoMessage() {}

func (x *AirlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirlineRequest.ProtoReflect.Descriptor instead.
func (*AirlineRequest) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{5}
}

type Airline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Airline) Reset() {
	*x = Airline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Airline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airline) ProtoMessage() {}

func (x *Airline) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airline.ProtoReflect.Descriptor instead.
func (*Airline) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{6}
}

type AirlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airline *Airline `protobuf:"bytes,1,opt,name=Airline,proto3" json:"Airline,omitempty"`
	Code    int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error   *Error   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AirlineResponse) Reset() {
	*x = AirlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_airline_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirlineResponse) ProtoMessage() {}

func (x *AirlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_airline_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirlineResponse.ProtoReflect.Descriptor instead.
func (*AirlineResponse) Descriptor() ([]byte, []int) {
	return file_admin_airline_proto_rawDescGZIP(), []int{7}
}

func (x *AirlineResponse) GetAirline() *Airline {
	if x != nil {
		return x.Airline
	}
	return nil
}

func (x *AirlineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AirlineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AirlineResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_admin_airline_proto protoreflect.FileDescriptor

var file_admin_airline_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x3d, 0x0a, 0x11, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x75,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x75, 0x70, 0x65, 0x22,
	0xb1, 0x02, 0x0a, 0x0a, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x2b,
	0x0a, 0x11, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x61, 0x6e, 0x75, 0x66,
	0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x6d,
	0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6d, 0x61, 0x6e, 0x75, 0x66,
	0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61,
	0x78, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x78,
	0x5f, 0x63, 0x72, 0x75, 0x69, 0x73, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x43, 0x72, 0x75, 0x69, 0x73, 0x65, 0x53, 0x70,
	0x65, 0x65, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x22,
	0x87, 0x01, 0x0a, 0x0f, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x07, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xe2, 0x02, 0x0a, 0x0c, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x43, 0x0a, 0x12, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_airline_proto_rawDescOnce sync.Once
	file_admin_airline_proto_rawDescData = file_admin_airline_proto_rawDesc
)

func file_admin_airline_proto_rawDescGZIP() []byte {
	file_admin_airline_proto_rawDescOnce.Do(func() {
		file_admin_airline_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_airline_proto_rawDescData)
	})
	return file_admin_airline_proto_rawDescData
}

var file_admin_airline_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_admin_airline_proto_goTypes = []interface{}{
	(*Error)(nil),               // 0: pb.Error
	(*FlightTypeRequest)(nil),   // 1: pb.FlightTypeRequest
	(*FlightType)(nil),          // 2: pb.FlightType
	(*FlightTypeResponse)(nil),  // 3: pb.FlightTypeResponse
	(*FlightTypesResponse)(nil), // 4: pb.FlightTypesResponse
	(*AirlineRequest)(nil),      // 5: pb.AirlineRequest
	(*Airline)(nil),             // 6: pb.Airline
	(*AirlineResponse)(nil),     // 7: pb.AirlineResponse
}
var file_admin_airline_proto_depIdxs = []int32{
	2,  // 0: pb.FlightTypeResponse.flight_type:type_name -> pb.FlightType
	0,  // 1: pb.FlightTypeResponse.error:type_name -> pb.Error
	2,  // 2: pb.FlightTypesResponse.fligh_types:type_name -> pb.FlightType
	0,  // 3: pb.FlightTypesResponse.error:type_name -> pb.Error
	6,  // 4: pb.AirlineResponse.Airline:type_name -> pb.Airline
	0,  // 5: pb.AirlineResponse.error:type_name -> pb.Error
	1,  // 6: pb.AdminAirline.RegisterFlightType:input_type -> pb.FlightTypeRequest
	1,  // 7: pb.AdminAirline.FetchAllFlightTypes:input_type -> pb.FlightTypeRequest
	1,  // 8: pb.AdminAirline.FetchFlightType:input_type -> pb.FlightTypeRequest
	1,  // 9: pb.AdminAirline.UpdateFlightType:input_type -> pb.FlightTypeRequest
	1,  // 10: pb.AdminAirline.DeleteFlightType:input_type -> pb.FlightTypeRequest
	3,  // 11: pb.AdminAirline.RegisterFlightType:output_type -> pb.FlightTypeResponse
	4,  // 12: pb.AdminAirline.FetchAllFlightTypes:output_type -> pb.FlightTypesResponse
	3,  // 13: pb.AdminAirline.FetchFlightType:output_type -> pb.FlightTypeResponse
	3,  // 14: pb.AdminAirline.UpdateFlightType:output_type -> pb.FlightTypeResponse
	3,  // 15: pb.AdminAirline.DeleteFlightType:output_type -> pb.FlightTypeResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_airline_proto_init() }
func file_admin_airline_proto_init() {
	if File_admin_airline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_airline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Airline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_airline_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_airline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_airline_proto_goTypes,
		DependencyIndexes: file_admin_airline_proto_depIdxs,
		MessageInfos:      file_admin_airline_proto_msgTypes,
	}.Build()
	File_admin_airline_proto = out.File
	file_admin_airline_proto_rawDesc = nil
	file_admin_airline_proto_goTypes = nil
	file_admin_airline_proto_depIdxs = nil
}
